modLoader="javafml"
loaderVersion="[39,)"
issueTrackerURL="https://github.com/Flaxbeard/ImmersivePetroleum/issues"
license="All rights reserved"

[[mods]] #mandatory
	modId="immersivepetroleum"
	version="${file.jarVersion}"
	displayName="Immersive Petroleum"
	displayURL="https://minecraft.curseforge.com/projects/immersive-petroleum"
	authors="Flaxbeard"
	description="Adds oil and oil processing features to Immersive Engineering."
	logoFile="logo.png"
	#updateJSONURL=""
	#credits=""

[[dependencies.immersivepetroleum]]
	modId="immersiveengineering"
	mandatory=true
	versionRange="[1.18.2-8.0.0-146,)"
	ordering="BEFORE"
	side="BOTH"

[[dependencies.immersivepetroleum]]
	modId="forge"
	mandatory=true
	versionRange="[40.0.12,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.immersivepetroleum]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.18.2]"
	ordering="NONE"
	side="BOTH"
